### ISSUE TITLE
TokenizeContext.sliceSerialize throws in sliceChunks if first chunk of token is Code instead of string

### ISSUE THREAD

**Issue by DavidAnson** [micromark/micromark#131]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark@3.1.0

### Steps to reproduce

```bash
user@HOST micromark-issue % npm ls micromark
micromark-issue@ /Users/user/micromark-issue
└── micromark@3.1.0

user@HOST micromark-issue % cat issue.mjs 
import { parse } from "micromark/lib/parse";
import { postprocess } from "micromark/lib/postprocess";
import { preprocess } from "micromark/lib/preprocess";

function repro(markdown) {
  console.log("trying...");
  const encoding = undefined;
  const end = true;
  const options = undefined;
  const chunks = preprocess()(markdown, encoding, end);
  const parseContext = parse(options).document().write(chunks);
  const events = postprocess(parseContext);
  for (const event of events) {
    const [ \_, token, context ] = event;
    context.sliceSerialize(token);
  }
  console.log("ok");
}

repro("Heading\\n=======");
repro("\\nHeading\\n=======");
user@HOST micromark-issue % node issue.mjs 
trying...
ok
trying...
file:///Users/user/micromark-issue/node\_modules/micromark/lib/create-tokenizer.js:520
      view[0] = view[0].slice(startBufferIndex)
                        ^

TypeError: view[0].slice is not a function
    at sliceChunks (file:///Users/user/micromark-issue/node\_modules/micromark/lib/create-tokenizer.js:520:25)
    at sliceStream (file:///Users/user/micromark-issue/node\_modules/micromark/lib/create-tokenizer.js:154:12)
    at Object.sliceSerialize (file:///Users/user/micromark-issue/node\_modules/micromark/lib/create-tokenizer.js:149:28)
    at repro (file:///Users/user/micromark-issue/issue.mjs:15:13)
    at file:///Users/user/micromark-issue/issue.mjs:21:1
    at ModuleJob.run (node:internal/modules/esm/module\_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm\_loader:88:5)
    at async handleMainPromise (node:internal/modules/run\_main:61:12)
user@HOST micromark-issue % 
```

### Expected behavior

`sliceSerialize` should always be safe to call in a manner like the above and should return a meaningful string. The presence of a leading `\n` in Markdown (for example) should not need to be guarded against by library users.

### Actual behavior

Exception, see above

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Hi!

Can you provide more info? I can’t reproduce:

`package.json`:

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "micromark": "^3.1.0"
  }
}
```

`example.js`:

```js
import { parse } from "micromark/lib/parse";
import { postprocess } from "micromark/lib/postprocess";
import { preprocess } from "micromark/lib/preprocess";

function repro(markdown) {
  console.log("trying...");
  const encoding = undefined;
  const end = true;
  const options = undefined;
  const chunks = preprocess()(markdown, encoding, end);
  const parseContext = parse(options).document().write(chunks);
  const events = postprocess(parseContext);
  for (const event of events) {
    const [ _, token, context ] = event;
    context.sliceSerialize(token);
  }
  console.log("ok");
}

repro("Heading\\n=======");
repro("\\nHeading\\n=======");
```

Running:

```sh
$ node -v; npm -v; node example.js 
```

Yields:

```
v19.3.0
9.2.0
trying...
ok
trying...
ok
```

**Comment by wooorm** [comment]
Oh wait, it’s the double escapes in your code

**Comment by wooorm** [comment]
You seem to be doing some fancy stuff with micromark, as this isn’t really normal use of the project. Care to elaborate what you’re doing with all the events?

**Comment by wooorm** [comment]
Locally in `node_modules`, this seems to solve it (create-tokenizer.js L573):

```js
if (startBufferIndex > -1) {
      const head = view[0]
      if (typeof head === 'string') {
        view[0] = head.slice(startBufferIndex)
      } else {
        assert(startBufferIndex === 0, 'expected `startBufferIndex` to be `0`')
        view.shift()
      }
    }
```

Haven’t tested in the micromark repo. But as this isn‘t something micromark normally does, it’s probably better if you check locally with your setup.

We might need some handling for the alternate case, the `if (endBufferIndex > 0) {` part.

**Comment by DavidAnson** [comment]
Thank you for having a look!

I think the output of "cat" made this confusing, sorry. Those aren't double escapes but just normal "newline" escapes in the string. Basically, if the initial heading does not begin on the first line, then I see the behavior reported here. You can reproduce the same thing reading the document from a file; that's how I originally found it.

What I'm doing is turning the linear Event sequence into a nested structure. I've linked the actual code at the bottom of this comment. This is part of an exploration for markdownlint to see if using a parser other than markdown-it can provide detailed line and column information for the document.

Preliminary investigation suggested that micromark emits this along with very granular information about that structure. It seems promising and I am literally just about to try incorporating it this evening. (First I had to deal with converting ESM to CommonJS because I don't want to give up a synchronous code path.)

I don't think I need anything else from micromark, but I'd like to have the text available for every node instead of having to try/catch like the linked function does today for cases like this.

By the way, I see the same crash in micromark for every Event marked with "_container". I'd love to see that behavior fixed as well, but originally assumed maybe it was by design for containers?

Thank you for the help, I hope this is useful!

https://github.com/DavidAnson/markdownlint/blob/mmdl/lib/micromark.cjs

**Comment by wooorm** [comment]
Ohh, you’re making a CST! Very cool. That was one of the design goals. But, haven’t had the time to really think about how the structure should look!

Yes, it should definitely improve linting. It would also allow formatting with just changes, such as `*` into `_`, or capitalizing some words or so, easier to do.

> ESM

I really really really suggest going with that, it’s the future, it’s ready!

---

There are two kinds of events: ones that wrap other events (headingSetext or so), and ones that contain only a couple of characters, and with enter/exit this “mimics” the tree structure, while being flat.
I recommend only serializing the events that contain text only.
It *should* all work of course (and I welcome PRs!), but this project *I believe* only works on the events containing texts.

---

Last, you might be interested in https://github.com/wooorm/markdown-rs. Takes the same approach, but it was my 2nd attempt at the algorithm, so it’s better. *And it’s rust* ;). I plan to move my improvements from that into here in the coming months.
The events there aren’t exposed yet (private by design), but here’s how to get them if you want to check it out in a fork: https://github.com/wooorm/markdown-rs/blob/2045b0bfc467efeb605aad7d8297a1fa1fc3e0e9/src/lib.rs#L145.

**Comment by DavidAnson** [comment]
My ideal for getting text for Events is that every “token“ I generate includes position information and the corresponding Markdown text. Here’s what that looks like now via the snapshot for the relevant test case: <https://github.com/DavidAnson/markdownlint/blob/mmdl/test/snapshots/markdownlint-test-micromark.mjs.md>. In practice, it may turn out that nobody looks at the text for wrapping elements like you suggest, but it would be nice to have it there. What’s frustrating about my example code above is that the setextHeading token may or may not have text associated with it based on whether there was a proceeding blank line to trigger this bug. That’s harder to deal with as a developer (and may lead to bugs) and I would rather promise that every token has text. As your proposed fix suggests, it may not take much code to patch the start/end checks and make this dream a reality. :)

The Rust implementation you link to is interesting, but I am pretty committed to the JavaScript ecosystem for the purposes of this discussion. I am glad to hear you may port improvements over!

Regarding ESM, I agree it is pleasant to use, BUT making the decision to convert a library imposes inconvenience on its users. They need to convert their code on someone else’s schedule and may need to give up synchronous code paths. Having been on the receiving end of this a few times, it’s not something I’m planning to do without strong justification.

**Comment by DavidAnson** [comment]
@wooorm, I sat down to write a quick test case for this scenario in the micromark repo, but I wasn't successful.

The main (only?) problem seems that `npm run build` after `npm i` in a fresh GitHub Codespace with the `HEAD` of `main` checked out fails with maybe 100 errors like the below. TypeScript (still) does not seem to have an easy way to suppress errors at scale.

The secondary (maybe mine?) problem is that `import {parse} from 'micromark/lib/parse'` fails for me from a new `.js` file in the `test` directory saying `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspaces/micromark/node_modules/micromark/lib/parse.js' imported from /workspaces/micromark/test/event.js`. Not knowing if this is related to the first problem, I didn't spend much time on it.

```
dev/lib/initialize/text.js:33:24 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

33     const constructs = this.parser.constructs[field]
                          ~~~~


Found 26 errors in 5 files.

Errors  Files
    17  dev/lib/compile.js:501
     1  dev/lib/initialize/content.js:21
     3  dev/lib/initialize/document.js:33
     3  dev/lib/initialize/flow.js:19
     2  dev/lib/initialize/text.js:32
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: micromark@3.1.0 
npm ERR!   at location: /workspaces/micromark/packages/micromark 
```

**Comment by DavidAnson** [comment]
By the way, I was able to run tests at one point, though I'm not sure it was valid, and there appeared to be 2 failures out of about 1500 tests. The scroll buffer wasn't long enough for me to easily see which two tests had failed.

**Comment by ChristianMurphy** [comment]
Both the typescript failures (TS4.9 changed how `this` is handled) and the failing test case (commonmark changed recently) are expected.
See https://github.com/micromark/micromark/pull/132 for a fix of the first of the two.

**Comment by DavidAnson** [comment]
Thanks, @ChristianMurphy! I'll wait until those issues get resolved to explore further.

**Comment by ChristianMurphy** [comment]
@DavidAnson Both TypeScript 4.9 and the commonmark test suite are passing again, if you want to take another look.

**Comment by DavidAnson** [comment]
@ChristianMurphy Nice, thank you!

**Comment by DavidAnson** [comment]
@wooorm, here is a potential PR for `micromark` to reproduce this issue. It includes a new test that validates the fix you propose above. I agree with you the `endBufferIndex` scenario may need a similar change, but I ran out of time tonight to explore that.

<https://github.com/micromark/micromark/compare/main...DavidAnson:micromark:sliceSerialize>

**Comment by DavidAnson** [comment]
I added another test just now (skipped by default) that exercises the same code for every Markdown file in the project (including dependencies). It passes, suggesting no additional changes are needed.

**Comment by DavidAnson** [comment]
Any thoughts? Should I raise a PR for the associated changes?

**Comment by wooorm** [comment]
Hi David! Thanks for your work.
The gist of it looks good, but your test is a bit different from the style used around here. Taking your work as inspiration, how about something like this as a file in `test/misc/slice-chunks.js`?:

```js
import test from 'tape'
import {parse} from 'micromark/lib/parse'
import {postprocess} from 'micromark/lib/postprocess'
import {preprocess} from 'micromark/lib/preprocess'

test('sliceSerialize', (t) => {
  t.deepEqual(
    parseAndSlice('Heading\n======='),
    [
      ['enter', 'setextHeading', 'Heading\n======='],
      ['enter', 'setextHeadingText', 'Heading'],
      ['enter', 'data', 'Heading'],
      ['exit', 'data', 'Heading'],
      ['exit', 'setextHeadingText', 'Heading'],
      ['enter', 'lineEnding', '\n'],
      ['exit', 'lineEnding', '\n'],
      ['enter', 'setextHeadingLine', '======='],
      ['enter', 'setextHeadingLineSequence', '======='],
      ['exit', 'setextHeadingLineSequence', '======='],
      ['exit', 'setextHeadingLine', '======='],
      ['exit', 'setextHeading', 'Heading\n=======']
    ],
    'should support `sliceSerialize` on a setext heading (#1)'
  )

  // This used to crash: <https://github.com/micromark/micromark/issues/131>.
  t.deepEqual(
    parseAndSlice('\nHeading\n======='),
    [
      ['enter', 'lineEndingBlank', '\n'],
      ['exit', 'lineEndingBlank', '\n'],
      ['enter', 'setextHeading', 'Heading\n======='],
      ['enter', 'setextHeadingText', 'Heading'],
      ['enter', 'data', 'Heading'],
      ['exit', 'data', 'Heading'],
      ['exit', 'setextHeadingText', 'Heading'],
      ['enter', 'lineEnding', '\n'],
      ['exit', 'lineEnding', '\n'],
      ['enter', 'setextHeadingLine', '======='],
      ['enter', 'setextHeadingLineSequence', '======='],
      ['exit', 'setextHeadingLineSequence', '======='],
      ['exit', 'setextHeadingLine', '======='],
      ['exit', 'setextHeading', 'Heading\n=======']
    ],
    'should support `sliceSerialize` on a setext heading (#2)'
  )

  t.end()
})

/**
 * Parse `value`, get all events, call `context.sliceSerialize` on each token.
 *
 * @param {string} value
 *   Input.
 * @returns {Array<[string, string, string]>}
 *   List of event kind, token names, and serialized slices.
 */
function parseAndSlice(value) {
  const chunks = preprocess()(value, undefined, true)
  const events = postprocess(parse().document().write(chunks))
  /** @type {Array<[string, string, string]>} */
  const result = []

  for (const event of events) {
    const [kind, token, context] = event
    result.push([kind, token.type, context.sliceSerialize(token)])
  }

  return result
}
```

Then, these two changes look very useful to have as a PR! The fix of course, and these test cases!

**Comment by DavidAnson** [comment]
Absolutely, thanks! I'll update my branch and send a proper PR in a few days.

**Comment by DavidAnson** [comment]
Link to PR: https://github.com/micromark/micromark/pull/137

CI tests are running now...
