### ISSUE TITLE
micromark crashes on invalid URI

### ISSUE THREAD

**Issue by ChristianMurphy** [micromark/micromark#19]
### Subject of the issue

Some malformed URL can crash micromark

### Your environment

*   **OS**: Ubuntu 16
*   **Packages**: micromark 2.6.0
*   **Env**: Node 14

### Steps to reproduce

```js
var micromark = require('micromark')

console.log(micromark('[](<%>)'))
```

originally detected with #18, credit to @wooorm for a more minimal repro

### Expected behavior

```
<p><a href="%25"></a></p>
```

### Actual behavior

```
URIError: URI malformed
    at decodeURI (<anonymous>)
    at normalizeUri (micromark/dist/util/normalize-uri.js:1:1040)
    at url (micromark/dist/compile/html.js:1:54303)
    at Object.onexitmedia (micromark/dist/compile/html.js:1:61812)
    at done (micromark/dist/compile/html.js:1:50389)
    at compile (micromark/dist/compile/html.js:1:48534)
    at buffer (micromark/dist/index.js:1:2192)
    at Worker.fuzz [as fn] (micromark/fuzzer.js:1:1781)
    at process.<anonymous> (micromark/node_modules/jsfuzz/build/src/worker.js:63:30)
```

**Comment by wooorm** [comment]
Well, that was an interesting deep-dive into uris! Fixed!
